version: 2.1

orbs:
  windows: circleci/windows@2.2.0

jobs:
  test:
    docker:
      - image: dotnet/aspnet
    description: Setup and run application tests
    executor:
      name: windows/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "circle-ci-example.csproj" }}
      - run:
          name: "Install project dependencies"
          command: dotnet.exe restore
      - save_cache:
          paths:
            - C:\Users\circleci\.nuget\packages
          key: dotnet-packages-v1-{{ checksum "circle-ci-example.csproj" }}
      - run:
          name: "Run Application Tests"
          command: dotnet.exe test -v n --results-directory:test_coverage --collect:"Code Coverage"
      - run:
          name: "Print Working Directory"
          command: pwd
      - store_artifacts:
          path: test_coverage
  build:
    docker:
    - image: dotnet/aspnet
    description: Build application with Release configuration
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: "Build Application according to some given configuration"
          command: dotnet.exe build --configuration Release
      - run:
          name: Deploy Over SSH
          command: | 
            scp [path] ssh user@127.0.0.1:/home/faridun/app
            ssh user@127.0.0.1 "sudo cp -rlf app/* /var/api/app-service/"
            ssh user@127.0.0.1 "sudo systemctl restart app-service.service"
workflows:
  test_and_build:
    jobs:
      - test
      - build:
          requires:
            - test